# Generated by Django 4.2.9 on 2024-01-23 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(error_messages={'dob': 'DOB required'}, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, error_messages={'department': 'Name required'}, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
    ]
