# Generated by Django 4.2.9 on 2024-01-23 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('employee', '0002_alter_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(error_messages={'department': 'Name required'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
    ]
