# Generated by Django 5.0.1 on 2024-01-22 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(error_messages={'date': 'Shift date is mandatory'}, verbose_name='shift from date')),
                ('from_time', models.TimeField(error_messages={'from_time': 'from time required'}, verbose_name='shift from time')),
                ('to_time', models.TimeField(error_messages={'to_time': 'to time require'}, verbose_name='shift to time')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(error_messages={'employee': 'Select the employee'}, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('location', models.ForeignKey(error_messages={'location': 'Select the location'}, on_delete=django.db.models.deletion.CASCADE, to='location.location')),
            ],
        ),
    ]
